apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-argocd-postgresql-password
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  key: {{ randAlphaNum 50 | quote }}
