apiVersion: v1
kind: Secret
metadata:
  name: sentry-argocd-postgresql-password
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
data:
  key: {{ randAlphaNum 50 | quote }}
