apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: sentry
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sentry
    repoURL: https://sentry-kubernetes.github.io/charts
    targetRevision: 15.0.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
