apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sentry
    repoURL: https://pulse00.github.io/sentry-charts
    targetRevision: 15.0.1-beta.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
