apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sentry
    repoURL: https://pulse00.github.io/sentry-charts
    targetRevision: 15.0.2
    helm:
      values: |-
        sentry:
          clickhouse:
            replicas: 1
          metrics:
            enabled: false
          rabbitmq:
            enabled: false
          nginx:
            enabled: true
          redis:
            replica:
              replicaCount: 1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
