apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  destination:
    namespace: sentry
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sentry
    repoURL: https://pulse00.github.io/sentry-charts
    targetRevision: 15.0.6
    helm:
      values: |-
        sentry:
          web:
            replicas: 1
            env:
            - name: SENTRY_EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sentry-email
                  key: user
            - name: SENTRY_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentry-email
                  key: password
          metrics:
            enabled: false
          nginx:
            enabled: true
        rabbitmq:
          enabled: false
        postgresql:
          existingSecret: postgres-sentry
          existingSecretKey: postgresql-password
        mail:
          backend: smtp
          useTls: false
          useSsl: true
          port: 465
          host: smtp.fastmail.com
          from: sentry-dev@example.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
